Added backbone, map constructor and changed environment.yml to includ…
adisingh50/raster-net pull request #11
Opened 2022-02-17 19:08 UTC by anshulcgm

- Created map constructor file that takes in a set of images and the pillar pixel map and creates the 3D feature map. 
- Unsure about what unit tests I should write
- Any suggestions to make correspondence map construction in create_feature_map more efficient?

2022-02-18 17:03 UTC, adisingh50 requested changes
Map constructor looks pretty good. Just some small requested changes here and there.

2022-02-18 18:54 UTC, adisingh50 commented on rasternet/bev_mapping/forward_projector.py
> +        #sampled_pillar_points = self.sample_pillar_points(ground_pillar_pts)
uncomment this line right? so that line 76 will execute properly

2022-02-18 19:23 UTC, adisingh50 commented on rasternet/bev_mapping/map_constructor.py
> +        flattened_feature_map = torch.reshape(feature_map, [N, -1, C])
and you can probably just keep the name `feature_map` since you're not really flattening anything here.

2022-02-20 18:16 UTC, anshulcgm commented on rasternet/bev_mapping/forward_projector.py
> +        indices = np.random.choice(ground_pillar_pts.shape[2], size = self.num_samples_per_pillar)
yep you're right, initially this was a 4D tensor, I just forgot to change it

2022-02-20 18:27 UTC, anshulcgm commented on rasternet/bev_mapping/forward_projector.py
> +        #sampled_pillar_points = self.sample_pillar_points(ground_pillar_pts)
no, im going to call sampling before and pass the result into this method for better modularity

2022-02-20 19:57 UTC, anshulcgm commented on rasternet/bev_mapping/map_constructor.py
> +        flattened_feature_map = torch.reshape(feature_map, [N, -1, C])
actually the docstring here was strong it's not a [N, C, HW] array it's [N, C, H, W] so I actually am flattening it

2022-02-20 23:32 UTC, adisingh50 commented on rasternet/bev_mapping/map_constructor.py
> +        flattened_feature_map = torch.reshape(feature_map, [N, -1, C])
ah got it.

2022-02-20 23:32 UTC, adisingh50 commented
LGTM

2022-02-20 23:38 UTC, merged