Map efficiency improvement
adisingh50/raster-net pull request #13
Opened 2022-02-24 02:05 UTC by anshulcgm

- Vectorized pillar pixel map construction
- Vectorized image pixel - feature pixels map construction
- Pillar Pixel map construction passes test case in forward projector but image pixel - feature map pixels map hasn't been tested yet. I'll write a test for it once Adi finishes the main test for the whole pipeline in test_map_constructor.py

2022-02-24 02:53 UTC, johnwlambert commented on rasternet/bev_mapping/map_constructor.py
> +        feature_map_indices = indices[:, 0] * feature_map.shape[3] + indices[:, 1]
nice work. `np.unravel_index`?

and a unit test on 1 dummy coord :- ) ? (maybe make a tiny helper to handle lines 46-56, so its easy to test)

2022-02-24 02:54 UTC, johnwlambert commented on rasternet/bev_mapping/map_constructor.py
> +        #     for j in range(height):
can we remove the dead code, if we have a replacement?

or, the dead code (slow method) could be used in the unit test : - )

2022-02-24 18:38 UTC, adisingh50 requested changes
These vectorized implementations will be super helpful for us. Just a few small comments from John and myself.

2022-02-24 18:38 UTC, adisingh50 commented on rasternet/bev_mapping/forward_projector.py
> +        image_indices = (real_img_coords[:, :, 1] * self.img_width + real_img_coords[:, :, 0]).astype(np.int32)
can we call this variable `flattened_image_indices`, since the coordinates are not (u,v) but a single integer. Also, let's add a comment at the end of line 177 like `# flattened_index = (v * img_width) + u` just to make this line clear for later reference.

2022-02-24 18:38 UTC, adisingh50 commented on rasternet/bev_mapping/forward_projector.py
>          # TODO: vectorize this!
remove this TODO

2022-02-24 18:38 UTC, adisingh50 commented on rasternet/bev_mapping/map_constructor.py
> +if __name__ == "__main__":
probably remove this test code once you feel that map_constructor is correctly vectorized

2022-02-24 18:38 UTC, adisingh50 commented on rasternet/bev_mapping/map_constructor.py
> +        #     for j in range(height):
good idea. You could feed an image through the inefficient implementation and then feed it through the vectorized implementation and verify the outputted `image_pixel_feature_map` are the same for both

2022-02-24 18:38 UTC, adisingh50 commented on rasternet/bev_mapping/map_constructor.py
> +        feature_map_indices = indices[:, 0] * feature_map.shape[3] + indices[:, 1]
I believe `np.unravel_index` converts flat array coords into tuple coordinates. Here, we want to do the opposite, so I think `np.ravel_multi_index` could be used here.

2022-02-25 02:53 UTC, anshulcgm commented on rasternet/bev_mapping/map_constructor.py
> +        feature_map_indices = indices[:, 0] * feature_map.shape[3] + indices[:, 1]
with either np.ravel_multi_index  or np.unravel_index, how would I multiply the 0th column by the image width and then add the height indices?

2022-02-25 03:00 UTC, adisingh50 commented on rasternet/bev_mapping/map_constructor.py
> +        feature_map_indices = indices[:, 0] * feature_map.shape[3] + indices[:, 1]
Personally, I'm okay with explicitly showing the multiplication `(v * img_width) + u`. It makes it clear what you're doing to obtain a flattened image index.

2022-02-25 03:15 UTC, anshulcgm commented on rasternet/bev_mapping/map_constructor.py
> +        #     for j in range(height):
Yea we'll use this code in the unit test. Right now Adi is working on a test in the map constructor file and we're trying to get an end to end pass through working for a single image by tomorrow so we are going to merge without a unit test for now. I will definitely get in a unit test by next week. I used pdb to go through it pretty thoroughly so I am confident it works for now.

2022-02-25 03:26 UTC, adisingh50 commented
LGTM. We will do a PR tomorrow that fixes black formatting. It seems that Anshul's formatter has some weird config that loves to turn 1 liners into 3 liners for no good reason.

2022-02-25 03:26 UTC, merged