Added stubs for mapping modules, adapted argoverse SE3 module for ras…
adisingh50/raster-net pull request #6
Opened 2022-02-02 04:06 UTC by anshulcgm

- Created stubs for mapping modules based off of notes in google doc
- Added in SE3 from argoverse-api repository for coordinate transformations, adapted module and tests for pytorch tensors instead of numpy arrays
- Added argoverse module to environment.yml file

Suggestions on mapping module organization would be appreciated, current organization feels kind of clunky.

2022-02-02 04:13 UTC, johnwlambert commented on rasternet/bev_mapping/modules.py
> +            rasterized_ground_height_map: A 2D tensor of shape [num_city_rows, num_city_columns] that contains ground height for every pixel in city coordinates
Thanks for the PR, Anshul.

Nit: max 120 char line length with `black rasternet/bev_mapping/modules.py -l 120`

2022-02-02 16:27 UTC, adisingh50 requested changes

2022-02-02 16:27 UTC, adisingh50 commented on rasternet/bev_mapping/modules.py
> +            map: A tensor of shape [horizontal_grid_size * vertical_grid_size, img_resolution_x * img_resolution_y] that represents
maybe include in the docstring that the outputted matrix will be sparse (at most a singular 1 in each row) and that 
`img_resolution_x * img_resolution_y  >>  horizontal_grid_size * vertical_grid_size`

2022-02-02 16:27 UTC, adisingh50 commented on tests/mapping/test_se3.py
> +    pts = np.array([[1.0, 1.0, 1.1], [1.0, 1.0, 2.1], [1.0, 1.0, 3.1]])
just initialize this as a torch tensor from the start?

2022-02-02 16:27 UTC, adisingh50 commented on tests/mapping/test_se3.py
> +if __name__ == "__main__":
do we need to explicitly call each of the test functions? In this [gtsfm test file](https://github.com/borglab/gtsfm/blob/master/tests/utils/test_io_utils.py), the functions are defined but not explicitly called in the code. I'm wondering if `pytest tests` will automatically run these functions for us? If not, then ignore this comment.

2022-02-02 16:28 UTC, johnwlambert commented on tests/mapping/test_se3.py
> +if __name__ == "__main__":
`pytest tests` will run all of the tests automatically that start with `test_*`

2022-02-02 16:28 UTC, adisingh50 commented on rasternet/bev_mapping/modules.py
> +class MapConstructor:
"map" can mean a lot of things. Let's call this `FeatureMapConstructor`

2022-02-02 16:34 UTC, adisingh50 commented on rasternet/bev_mapping/modules.py
> +            correspondence_map: A tensor of shape [img_resolution_x * img_resolution_y, feature_map_resolution_x * feature_map_resolution_y]
maybe state in docstring that this matrix should also be sparse (single entry 1 per row). Since every original input image pixel can only map to one feature map vector.

2022-02-03 17:21 UTC, adisingh50 commented
Also one last nitpick is let's keep the directory structure within `rasternet` identical to the directory structure within `tests`. So, move `test_se3.py` out of `mapping` directory, make a new `utils` folder on the same level as `perceiver_io` and move `test_s3.py` into that `utils` folder.

2022-02-03 20:15 UTC, anshulcgm commented on rasternet/bev_mapping/modules.py
> +            ground_pillars: A tensor of shape [horizontal_grid_size, vertical_grid_size, num_pillars, 3] that contains points that make up each pillar in city coordinates
yea the naming is just confusing, it should be num_pts_per_pillar instead of num_pillars

2022-02-03 20:17 UTC, anshulcgm commented on tests/mapping/test_se3.py
> +    pts = np.array([[1.0, 1.0, 1.1], [1.0, 1.0, 2.1], [1.0, 1.0, 3.1]])
the initial tests for SE3 use numpy arrays, I tried to make as few modifications as possible

2022-02-04 01:57 UTC, adisingh50 commented on rasternet/bev_mapping/modules.py
> +            ground_pillars: A tensor of shape [horizontal_grid_size, vertical_grid_size, num_pillars, 3] that contains points that make up each pillar in city coordinates
cool

2022-02-04 02:03 UTC, adisingh50 commented on tests/mapping/test_se3.py
> +    pts = np.array([[1.0, 1.0, 1.1], [1.0, 1.0, 2.1], [1.0, 1.0, 3.1]])
makes sense.

2022-02-04 02:07 UTC, adisingh50 commented
Changes in code and organizational structure look good to me.

2022-02-04 02:07 UTC, merged